#!/bin/zsh

REPOSITORIES=`pwd`

IFS=$'\n'

for REPO in `ls "$REPOSITORIES/"`
do
  if [ -d "$REPOSITORIES/$REPO" ]
  then
    if [ -d "$REPOSITORIES/$REPO/.git" ]
    then
        cd "$REPOSITORIES/$REPO/.git"
        set-gitconfig
    else
        echo "Skipping $REPO"
    fi
  fi
done
