#!/bin/zsh

REPOSITORIES=`pwd`

IFS=$'\n'

for REPO in `ls "$REPOSITORIES/"`
do
  if [ -d "$REPOSITORIES/$REPO" ]
  then
    if [ -d "$REPOSITORIES/$REPO/.git" ]
    then
        echo "Pulling $REPO"
        cd "$REPOSITORIES/$REPO"
        git rp
    else
        echo "Skipping $REPO"
    fi
  fi
done
