#!/bin/zsh

## Languages
brew install nvm rbenv lua python

## Parsing
brew install jq readline

## Searching
brew install fzf ripgrep fd

## Tmux 
brew install tmux tmuxinator

## Libraries 
brew install gh

