#!/bin/zsh

DIR=$HOME/.dotfiles

DOTFILES=(
    ".zshrc"
    ".tmux.conf"
    ".ssh/config"
    ".config/nvim"
    ".config/tmuxinator"
)

for dotfile in "${DOTFILES[@]}";do
        if [ -L "${HOME}/${dotfile}" ]; then
            echo "NOT TOUCHING ${HOME}/${dotfile}"
        else
            if [ -f "${HOME}/${dotfile}" ]; then
                echo "REMOVING ${dotfile}"
                rm -f "${HOME}/${dotfile}"
            fi
            ln -sfn "${DIR}/${dotfile}" "${HOME}/${dotfile}"
            echo "SYMLINK MADE FOR ${dotfile}"
        fi
done
