#!/bin/zsh
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh --no-use | zsh
nvm install node 
nvm use node
npm install -g npx
npm install -g yarn
npm install -g intelephense
npm install -g pyright
npm install -g typescript-language-server
