#!/bin/zsh

DIR=$HOME/.dotfiles

DOTFILES=(
    ".zshrc"
    ".tmux.conf"
    ".gitconfig"
    ".config/nvim"
    ".config/tmuxinator"
    ".config/skhd"
    ".ssh/config"
    ".yabairc"
)

LOCATIONS=(

)

for dotfile in "${DOTFILES[@]}";do
	rm -rf "${HOME}/${dotfile}"
	ln -sf "${DIR}/${dotfile}" "${HOME}/${dotfile}"
done
