#!/bin/zsh


FILES=(
    ".dotfiles"
    "vimwiki"
)

for file in "${FILES[@]}";do
	rm -rf "${HOME}/my-dev/${file}"
	ln -sf "${HOME}/${file}" "${HOME}/my-dev/${file}"
done

rm -rf "${HOME}/my-dev/nvim"
ln -sf "${HOME}/.dotfiles/.config/nvim" "${HOME}/my-dev/nvim"
