#!/bin/zsh

DIR=$HOME/.dotfiles

DOTFILES=(
    ".bin"
    ".bashrc"
    ".zprofile"
    ".tmux.conf"
    ".gitconfig"
    ".config/nvim"
    ".config/tmuxinator"
    ".config/skhd"
    ".ssh/config"
    ".yabairc"
)

for dotfile in "${DOTFILES[@]}";do
	rm -rf "${HOME}/${dotfile}"
	ln -sf "${DIR}/${dotfile}" "${HOME}/${dotfile}"
done

if [ ! -f ~/.zshrc ]; then
    cp "${DIR}/.zshrc" "${HOME}/.zshrc"
fi


