#!/bin/zsh

DATA="${HOME}/.dotfiles/.data/repos.txt"

echo "\n\n"
for REPO in `cat "${DATA}"`; do
    echo "$REPO"
    REPO_PATH="${HOME}/${REPO}"
    cd "$REPO_PATH"
    git pull
    echo "\n\n"
done
