#!/bin/zsh

DATA="${HOME}/.dotfiles/.data/repos.txt"

echo "\n\n"
for REPO in `cat "${DATA}"`; do
    echo "$REPO"
    REPO_PATH="${HOME}/${REPO}"
    cd "$REPO_PATH"
    git add .
    git commit -m "Script update on `date`"
    git push
    echo "\n\n"
done
