#!/bin/zsh

DATA="${HOME}/.dotfiles/.data/repos.txt"

for REPO in `cat "${DATA}"`; do
    REPO_PATH="${HOME}/${REPO}"
    echo "Updating $REPO_PATH at `date`"
    git add .
    git commit -m "Script update on `data`"
    git push
done
