#!/bin/zsh

REPOSITORIES=`pwd`

IFS=$'\n'

for REPO in `ls "$REPOSITORIES/"`
do
  if [ -d "$REPOSITORIES/$REPO" ]
  then
    if [ -d "$REPOSITORIES/$REPO/.git" ]
    then
        cd "$REPOSITORIES/$REPO"
        echo "Pushing to $REPO"
        git add .
        git commit -m "Script update on `date`"
        git push
    else
        echo "Skipping $REPO"
    fi
  fi
done
