#!/bin/zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    env=$(cat $HOME/.dotfiles/.data/env)
    if [[ $env == "personal" ]]; then
        find ~/development/ ~/my-dev -mindepth 1 -maxdepth 1 -type d > $HOME/.dotfiles/.data/sesh-input
        cat $HOME/.dotfiles/.data/sesh-more-input >>  $HOME/.dotfiles/.data/sesh-input
        selected=$(cat $HOME/.dotfiles/.data/sesh-input | fzf --delimiter / --with-nth -1)
        exit 0
    fi
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s etsy
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
