#!/bin/zsh
if tmux has-session -t watch > /dev/null 2>&1; then
else
    tmux new-session -ds watch -c ~/.dotfiles -n pull
    tmux send-keys -t pull "git rp" C-m
    tmux new-window -t pull "git rp" C-m
    tmux send-keys -t watch "gitwatch ." C-m
fi

